language: node_js
os: linux
node_js:
  - '10'
before_deploy:
  - yarn build --hosting-url $HOSTING_URL
deploy:
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_PAGES_TOKEN
    local_dir: ./build/rc
    email: 'integrations@ringcentral.com'
    name: 'RingCentral Integrations Team'
    on:
      branch: master
